import fs from 'fs';

function cmd(id, name, category, tier, syntax, description, example, exampleOutput, dangerLevel, tags) {
  return { id, name, category, tier, syntax, description, example, exampleOutput, dangerLevel, tags };
}

const list = [];

// 9. SYSTEM & ENVIRONMENT (38 commands)
list.push(
  cmd("uname", "uname", "system", "newbie", "uname [-a -m -r]", "Prints kernel name, architecture, and system release information.", "uname -a", "Linux localhost 6.1.45-android14-9 #1 SMP PREEMPT aarch64 Android", "safe", ["system", "kernel", "arch"]),
  cmd("whoami", "whoami", "system", "newbie", "whoami", "Displays the effective username of the current user session.", "whoami", "u0_a245", "safe", ["system", "user", "identity"]),
  cmd("id", "id", "system", "basic", "id [-u -g -G]", "Prints real and effective user ID (UID) and group IDs (GID).", "id", "uid=10245(u0_a245) gid=10245(u0_a245) groups=10245,3003(inet),9997", "safe", ["user", "uid", "gid", "permissions"]),
  cmd("hostname", "hostname", "system", "newbie", "hostname", "Shows or sets the system's network hostname.", "hostname", "localhost", "safe", ["system", "host", "network"]),
  cmd("uptime", "uptime", "system", "newbie", "uptime", "Tells how long the system has been running, user count, and load averages.", "uptime", " 10:30:15 up 4 days, 12:10,  1 user,  load average: 1.42, 0.98, 0.85", "safe", ["uptime", "system", "load"]),
  cmd("date", "date", "system", "newbie", "date [+\"%Y-%m-%d %H:%M:%S\"]", "Displays or formats the current system date and time.", "date", "Mon Aug 17 10:30:00 UTC 2026", "safe", ["date", "time", "clock"]),
  cmd("cal", "cal", "system", "newbie", "cal [-3 | -y]", "Displays a formatted monthly or yearly calendar grid in the terminal.", "cal", "    August 2026\nSu Mo Tu We Th Fr Sa\n                   1\n 2  3  4  5  6  7  8\n 9 10 11 12 13 14 15\n16 17 18 19 20 21 22", "safe", ["calendar", "date"]),
  cmd("lscpu", "lscpu", "system", "basic", "lscpu", "Displays detailed CPU architecture, core counts, clocks, and cache topology.", "lscpu | head -n 8", "Architecture:          aarch64\nCPU op-mode(s):        32-bit, 64-bit\nByte Order:            Little Endian\nCPU(s):                8\nModel name:            Cortex-X4 + Cortex-A720", "safe", ["cpu", "hardware", "architecture"]),
  cmd("free", "free", "system", "newbie", "free [-h -m]", "Displays total, used, and available physical RAM and swap space in human units.", "free -h", "               total        used        free      shared  buff/cache   available\nMem:           7.4Gi       2.8Gi       3.1Gi        42Mi       1.5Gi       4.3Gi\nSwap:          4.0Gi       120Mi       3.8Gi", "safe", ["ram", "memory", "free", "swap"]),
  cmd("vmstat", "vmstat", "system", "normal", "vmstat [delay [count]]", "Reports information about processes, memory, paging, block IO, and CPU activity.", "vmstat 1 2", "procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----\n r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st\n 1  0 122880 3241000  42100 1542000    0    0    12    45  420  980  4  1 95  0  0", "safe", ["memory", "vmstat", "performance"]),
  cmd("dmesg", "dmesg", "system", "advanced", "dmesg [-T | --level=err]", "Reads and prints the kernel ring buffer messages and boot logs.", "dmesg | tail -n 4", "[12345.678] type=1400 audit(1723880000.124:99): avc: granted { read }", "warning", ["kernel", "dmesg", "logs", "hardware"]),
  cmd("env", "env", "system", "basic", "env", "Prints all exported environment variables in the current shell session.", "env | head -n 6", "PREFIX=/data/data/com.termux/files/usr\nHOME=/data/data/com.termux/files/home\nSHELL=/data/data/com.termux/files/usr/bin/bash\nPATH=/data/data/com.termux/files/usr/bin", "safe", ["environment", "variables", "env"]),
  cmd("export", "export", "system", "newbie", "export <VAR_NAME>=<value>", "Sets and exports shell environment variables to child processes.", "export EDITOR=nano", "$ echo $EDITOR\nnano", "safe", ["environment", "export", "shell"]),
  cmd("printenv", "printenv", "system", "newbie", "printenv [VARIABLE]", "Prints specific or all environment variable values.", "printenv PREFIX", "/data/data/com.termux/files/usr", "safe", ["environment", "printenv"]),
  cmd("alias", "alias", "system", "newbie", "alias <name>='<command>'", "Creates shorthand aliases for complex or long command strings.", "alias ll='ls -la --color=auto'", "$ ll\ntotal 24", "safe", ["alias", "shortcuts", "shell"]),
  cmd("unalias", "unalias", "system", "basic", "unalias <alias_name>", "Removes an active shell shortcut alias definition.", "unalias ll", "$ echo $?\n0", "safe", ["alias", "unalias", "shell"]),
  cmd("which", "which", "system", "newbie", "which <command>", "Locates the executable binary file associated with a command in $PATH.", "which python", "/data/data/com.termux/files/usr/bin/python", "safe", ["which", "path", "binary"]),
  cmd("whereis", "whereis", "system", "basic", "whereis <command>", "Locates the binary, source, and manual page files for a command.", "whereis bash", "bash: /data/data/com.termux/files/usr/bin/bash /usr/share/man/man1/bash.1.gz", "safe", ["whereis", "lookup", "binary"]),
  cmd("whatis", "whatis", "system", "basic", "whatis <command>", "Displays one-line manual page descriptions.", "whatis curl", "curl (1) - transfer a URL", "safe", ["whatis", "man", "description"]),
  cmd("man", "man", "system", "basic", "man <command>", "Formats and displays the on-line manual documentation pages.", "man ls", "LS(1) User Commands LS(1)\nNAME\n       ls - list directory contents", "safe", ["man", "manual", "docs"]),
  cmd("history", "history", "system", "newbie", "history [-c | -w]", "Displays the session history list of executed commands with line numbers.", "history | tail -n 4", " 101  pkg update\n 102  pkg install git\n 103  git clone repo\n 104  history", "safe", ["history", "bash", "commands"]),
  cmd("clear", "clear", "system", "newbie", "clear", "Clears the terminal screen viewport buffer.", "clear", "\u001b[H\u001b[2J\u001b[3J", "safe", ["clear", "terminal", "screen"]),
  cmd("reset", "reset", "system", "basic", "reset", "Reinitializes the terminal state and cures broken character rendering.", "reset", "[*] Terminal reinitialized.", "safe", ["reset", "terminal"]),
  cmd("sleep", "sleep", "system", "newbie", "sleep <duration[s|m|h]>", "Delays execution for a specified amount of time.", "sleep 2 && echo 'Awake'", "Awake", "safe", ["sleep", "delay", "timer"]),
  cmd("echo", "echo", "system", "newbie", "echo [-e -n] <text>", "Outputs strings or variable expansions to standard output.", "echo \"User: $USER on $(date +%A)\"", "User: u0_a245 on Monday", "safe", ["echo", "output", "print"]),
  cmd("printf", "printf", "system", "basic", "printf '<format>' [arguments]", "Formats and prints data using C-style format strings.", "printf \"%-10s: %04d\\n\" \"Index\" 42", "Index     : 0042", "safe", ["printf", "format", "string"]),
  cmd("basename", "basename", "system", "basic", "basename <path> [suffix]", "Strips directory prefixes and suffixes from filenames.", "basename /home/user/script.py .py", "script", "safe", ["file", "path", "basename"]),
  cmd("dirname", "dirname", "system", "basic", "dirname <path>", "Strips non-directory suffix from file path, returning parent folder.", "dirname /home/user/script.py", "/home/user", "safe", ["file", "path", "dirname"]),
  cmd("realpath", "realpath", "system", "basic", "realpath <path>", "Resolves symlinks and prints the canonical absolute path.", "realpath ~/storage/shared", "/sdcard", "safe", ["path", "realpath", "symlink"]),
  cmd("bc", "bc", "system", "basic", "bc -l", "Arbitrary precision calculator language in the terminal.", "echo \"scale=4; 355/113\" | bc -l", "3.1415", "safe", ["math", "calculator", "bc"]),
  cmd("tsu", "tsu", "system", "advanced", "tsu [command]", "Root wrapper for Termux on rooted Android devices (replaces standard su).", "tsu -c id", "uid=0(root) gid=0(root) groups=0(root)", "warning", ["root", "superuser", "tsu"])
);

// 10. SECURITY & CRYPTO (15 commands)
list.push(
  cmd("openssl", "openssl", "security", "normal", "openssl [req|x509|enc|genpkey] ...", "Cryptography toolkit implementing SSL/TLS and key generation.", "openssl rand -hex 16", "a9f4c3d821e7b0a51c4e8f9d023b6a1e", "safe", ["crypto", "ssl", "tls", "security"]),
  cmd("gpg", "gpg", "security", "normal", "gpg [--gen-key | --encrypt | --decrypt]", "GNU Privacy Guard OpenPGP encryption and signing tool.", "gpg --version | head -n 1", "gpg (GnuPG) 2.4.5", "safe", ["gpg", "pgp", "encryption", "keys"]),
  cmd("age", "age", "security", "normal", "age [-e -r recipient | -d] <file>", "Simple, modern and secure file encryption tool with small keys.", "age -p secret.txt > secret.txt.age", "[*] Enter passphrase: [hidden]\n[+] File encrypted.", "safe", ["encryption", "age", "security"]),
  cmd("sqlmap", "sqlmap", "security", "advanced", "sqlmap -u <url> --batch --banner", "Automatic SQL injection and database vulnerability testing tool.", "sqlmap -u 'http://testphp.vulnweb.com/listproducts.php?cat=1' --batch", "[*] testing connection to the target URL\n[+] GET parameter 'cat' is vulnerable to SQL injection.", "warning", ["sql", "security", "audit", "pentest"]),
  cmd("hydra", "hydra", "security", "advanced", "hydra -l user -P passwords.txt <target> <service>", "Very fast network logon security audit cracker.", "hydra -l admin -P pass.txt 192.168.1.1 http-get /admin", "[DATA] attacking http-get://192.168.1.1:80/admin\n[80][http-get] host: 192.168.1.1   login: admin   password: password123", "warning", ["security", "audit", "hydra", "passwords"]),
  cmd("john", "john (the ripper)", "security", "advanced", "john [--wordlist=dict.txt] <hashfile>", "Fast password hash cracker and security auditing tool.", "john hashes.txt", "Loaded 1 password hash (bcrypt)\npassword123      (admin)\n1g 0:00:00:02 0.49g/s", "warning", ["crypto", "hashes", "security"]),
  cmd("exiftool", "exiftool", "security", "basic", "exiftool [-all=] <image.jpg>", "Reads, writes, and sanitizes EXIF privacy metadata from photos and media.", "exiftool -GPSPosition photo.jpg", "GPS Position : 37 deg 46' 29.64\" N, 122 deg 25' 9.84\" W", "safe", ["exif", "privacy", "metadata", "image"]),
  cmd("steghide", "steghide", "security", "normal", "steghide embed -cf cover.jpg -ef secret.txt", "Steganography program that hides secret data inside image and audio files.", "steghide embed -cf photo.jpg -ef notes.txt", "Enter passphrase: \nembedding \"notes.txt\" in \"photo.jpg\"... done", "safe", ["steganography", "security", "privacy"]),
  cmd("nikto", "nikto", "security", "advanced", "nikto -h <host>", "Web server vulnerability scanner checking for dangerous files and outdated software.", "nikto -h http://127.0.0.1:8080", "+ Target IP: 127.0.0.1\n+ Server: nginx/1.24.0\n+ No CGI Directories found", "warning", ["security", "web", "scanner", "vulnerability"])
);

// 11. CLI FUN & AESTHETICS (18 commands)
list.push(
  cmd("neofetch", "neofetch", "cli-fun", "newbie", "neofetch", "CLI system information tool displaying ASCII art logo and hardware specs.", "neofetch", "       _--_         u0_a245@localhost\n     /      \\       -----------------\n    |        |      OS: Termux (Android 14)\n     \\      /       Host: Galaxy S24 Ultra\n       `--'         Kernel: 6.1.45-android\n                    Uptime: 4 days\n                    Packages: 142 (dpkg)\n                    Shell: bash 5.2.26\n                    Memory: 2840MiB / 7600MiB", "safe", ["aesthetic", "specs", "neofetch", "ascii"]),
  cmd("fastfetch", "fastfetch", "cli-fun", "newbie", "fastfetch", "Ultra-fast C-written modern neofetch alternative with GPU and Vulkan telemetry.", "fastfetch", "termux@android\n--------------\nOS: Android 14 (Termux aarch64)\nDevice: Samsung Galaxy\nCPU: ARMv9 8 Cores @ 3.39GHz\nMemory: 2.78 GiB / 7.42 GiB (37%)", "safe", ["fastfetch", "specs", "aesthetic", "c"]),
  cmd("cmatrix", "cmatrix", "cli-fun", "newbie", "cmatrix [-b -C green|red|cyan]", "Generates falling Matrix digital rain code in your terminal.", "cmatrix -b", "ﾊ ﾐ ﾋ ｰ ｳ ｼ ﾅ ﾓ ﾆ ｻ ﾜ ﾂ ｵ ﾘ ｱ ﾎ ﾃ ﾏ ｹ ﾒ ｴ ｶ ｷ ﾑ ﾕ ﾗ ｾ ﾈ ｽ ﾀ ﾇ ﾍ\n: ・ . \" = * + - < >", "safe", ["fun", "matrix", "animation", "retro"]),
  cmd("sl", "sl (steam locomotive)", "cli-fun", "newbie", "sl [-a -F -e]", "Drives an animated steam train across your terminal screen when you mistype 'ls'.", "sl", "      ====        ________                ___________ \n  _D _|  |_______/        \\__I_I_____===__|_________| \n   |(_)---  |   H\\________/ _____ |   |===|   |   |   \n   /     |===========|   |_____| |===|   |   |   |", "safe", ["fun", "train", "animation"]),
  cmd("cowsay", "cowsay", "cli-fun", "newbie", "cowsay [-f cowfile] <message>", "Generates an ASCII talking cow containing customizable quote bubbles.", "cowsay 'Termux rules!'", " ______________\n< Termux rules! >\n --------------\n        \\   ^__^\n         \\  (oo)\\_______\n            (__)\\       )\\/\\\n                ||----w |\n                ||     ||", "safe", ["fun", "cowsay", "ascii"]),
  cmd("fortune", "fortune", "cli-fun", "newbie", "fortune", "Prints random humorous quotes, proverbs, and fortune cookie pearls.", "fortune", "A clean desk is a sign of a cluttered desk drawer.", "safe", ["fun", "quotes", "fortune"]),
  cmd("lolcat", "lolcat", "cli-fun", "newbie", "echo <text> | lolcat", "Rainbow gradient colorizer filter for terminal text output.", "fortune | cowsay | lolcat", "🌈 [Vibrant colored rainbow cow quote] 🌈", "safe", ["fun", "rainbow", "colors", "aesthetic"]),
  cmd("figlet", "figlet", "cli-fun", "newbie", "figlet [-f font] <text>", "Generates large stylized ASCII banner headers from standard text.", "figlet 'TERMUX'", " _____ _____ ____  __  __ _   ___  __\n|_   _| ____|  _ \\|  \\/  | | | \\ \\/ /\n  | | |  _| | |_) | |\\/| | | | |\\  / \n  | | | |___|  _ <| |  | | |_| |/  \\ \n  |_| |_____|_| \\_\\_|  |_|\\___//_/\\_\\", "safe", ["fun", "ascii", "figlet", "banner"]),
  cmd("toilet", "toilet", "cli-fun", "newbie", "toilet -f mono12 -F border <text>", "Enhanced banner text generator with colored Unicode fonts and borders.", "toilet -f standard 'HACK'", "┌────────────────────────┐\n│  _   _    _    ____ _  │\n│ | | | |  / \\  / ___| | │\n│ | |_| | / _ \\| |   | | │\n│ |  _  |/ ___ \\ |___|_| │\n│ |_| |_/_/   \\_\\____(_) │\n└────────────────────────┘", "safe", ["fun", "toilet", "banner", "ascii"]),
  cmd("pipes.sh", "pipes.sh", "cli-fun", "newbie", "pipes.sh", "Animated screen-saver of colorful 3D pipes navigating the terminal.", "pipes.sh", "╔══╗  ╔════╗\n║  ╚══╝    ║\n╚══════════╝", "safe", ["fun", "pipes", "screensaver"]),
  cmd("cbonsai", "cbonsai", "cli-fun", "newbie", "cbonsai [-l -m 'message']", "Grows an animated procedural ASCII Bonsai tree directly in your terminal.", "cbonsai -l", "       &&& &&  & &&\n    && &\\/&\\|() ()/ @\n     &\\/(/&/&||/& /_/)_&\n  @()&/&&& & ()|/& /_%\n      &_\\_&&_\\ |& |&&/&\n        &&   \\|||\n              |||\n              |||\n        ______|||______\n       |_______________|", "safe", ["fun", "bonsai", "art", "aesthetic"])
);

fs.writeFileSync('./scripts/commands-part4.json', JSON.stringify(list, null, 2));
console.log('Part 4 generated:', list.length);
